[package]
name = "sys-locale"
version = "0.3.1"
authors = ["1Password"]
description = "Small and lightweight library to obtain the active system locale"
keywords = ["locale", "i18n", "localization", "nostd"]
repository = "https://github.com/1Password/sys-locale"
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.'cfg(target_os = "android")'.dependencies]
libc = "0.2"

[target.'cfg(all(target_family = "wasm", not(unix)))'.dependencies]
js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", features = ["Window", "WorkerGlobalScope", "Navigator", "WorkerNavigator"], optional = true }

[features]
js = ["js-sys", "wasm-bindgen", "web-sys"]

[target.'cfg(all(target_family = "wasm", not(unix)))'.dev-dependencies]
wasm-bindgen-test = "0.3"